name: Enforce Community Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-community-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for required files
        id: file_check
        run: |
          REQUIRED_FILES=(
            "CODE_OF_CONDUCT.md"
            "CONTRIBUTING.md"
            "SUPPORT.md"
          )
          
          MISSING_FILES=""
          
          for FILE in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$FILE" ]; then
              MISSING_FILES="$MISSING_FILES $FILE"
            fi
          done
          
          echo "missing_files=$MISSING_FILES" >> $GITHUB_OUTPUT

      - name: Fail if files are missing
        if: steps.file_check.outputs.missing_files != ''
        run: |
          echo "The following required files are missing from the repository: ${{ steps.file_check.outputs.missing_files }}"
          exit 1
