name: Enforce Community Files

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-community-files:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for required files
        id: file_check
        run: |
          REQUIRED_FILES=(
            "README.md"
            "SUPPORT.md"
          )
          
          MISSING_FILES=""
          
          for FILE in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$FILE" ]; then
              MISSING_FILES="$MISSING_FILES $FILE"
            fi
          done
          
          echo "missing_files=$MISSING_FILES" >> $GITHUB_OUTPUT

      - name: Fail if files are missing
        if: steps.file_check.outputs.missing_files != ''
        run: |
          echo "The following required files are missing from the repository: ${{ steps.file_check.outputs.missing_files }}"
          exit 1

      - name: Create issue on failure
        if: ${{ failure() }}
        run: |
          gh issue create --title "Missing community file" --body "This issue was created automatically this repository is missing mandatory files: ${{ steps.file_check.outputs.missing_files }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
